[package]
name = "rust-challenge"
version = "0.1.0"
authors = ["Gary Mansell <gary.mansell@cyberlytic.com>"]

[dependencies]
futures = "0.1.14"
hyper = "0.11.0"
tokio-process = "0.1.3"
tokio-io = "0.1"