[package]
name = "process_supervisor"
version = "0.1.0"
authors = ["Gary Mansell <gary.mansell@cyberlytic.com>"]

[dependencies]
# tokio-core = "0.1"
tokio-process = "0.1.3"
serde = "0.9"
serde_derive = "0.9"